Repository SeedSigner/seedsigner, pull requests merged in 2023-08, with the labels that each got.

#394 SettingsQR: Final changes before official release
  src/seedsigner/gui/screens/scan_screens.py
  src/seedsigner/models/decode_qr.py
  src/seedsigner/models/settings.py
  src/seedsigner/models/settings_definition.py
  src/seedsigner/views/scan_views.py
  src/seedsigner/views/settings_views.py
  tests/test_flows_seed.py
  tests/test_settings.py
  tests/test_settingsqr_decoder.py
Labels: enhancement

#403 Dice doc
  docs/dice_verification.md
  docs/img/dicedoc/coleman_addresses.png
  docs/img/dicedoc/coleman_change_addresses_1.png
  docs/img/dicedoc/coleman_change_addresses_2.png
  docs/img/dicedoc/coleman_entropy.png
  docs/img/dicedoc/coleman_verify.png
  docs/img/dicedoc/coleman_zpub.png
  docs/img/dicedoc/seedtool_1.png
  docs/img/dicedoc/seedtool_2.png
  docs/img/dicedoc/seedtool_3.png
  docs/img/dicedoc/seedtool_addresses.png
  docs/img/dicedoc/seedtool_change_addresses_1.png
  docs/img/dicedoc/seedtool_change_addresses_2.png
  docs/img/dicedoc/seedtool_fingerprint.png
  docs/img/dicedoc/seedtool_zpub.png
  docs/img/dicedoc/sesi_dice_1.png
  docs/img/dicedoc/sesi_dice_2.png
  docs/img/dicedoc/sesi_export_xpub_1.png
  docs/img/dicedoc/sesi_export_xpub_2.png
  docs/img/dicedoc/sesi_finger_print.png
  docs/img/dicedoc/sesi_seed_1.png
  docs/img/dicedoc/sesi_seed_2.png
  docs/img/dicedoc/sesi_tools_dice_seed.png
  docs/img/dicedoc/sparrow_wallet_1.png
  docs/img/dicedoc/sparrow_wallet_2.png
  docs/img/dicedoc/sparrow_zpub.png
Labels: documentation

#421 Add back WarningScreen import in psbt_views.py
  src/seedsigner/views/psbt_views.py
Labels: bug

#420 Update ST7789 to support writing to larger SPIDEV buffer
  docs/manual_installation.md
  src/seedsigner/gui/screens/scan_screens.py
  src/seedsigner/hardware/ST7789.py
Labels: documentation, enhancement

#416 [Enhancement] Speed up initial module imports
  src/seedsigner/controller.py
  src/seedsigner/gui/components.py
  src/seedsigner/gui/renderer.py
  src/seedsigner/gui/screens/scan_screens.py
  src/seedsigner/gui/screens/screen.py
  src/seedsigner/gui/screens/seed_screens.py
  src/seedsigner/hardware/buttons.py
  src/seedsigner/hardware/camera.py
  src/seedsigner/helpers/mnemonic_generation.py
  src/seedsigner/models/__init__.py
  src/seedsigner/models/decode_qr.py
  src/seedsigner/models/encode_qr.py
  src/seedsigner/models/psbt_parser.py
  src/seedsigner/models/seed.py
  src/seedsigner/models/seed_storage.py
  src/seedsigner/models/settings.py
  src/seedsigner/views/psbt_views.py
  src/seedsigner/views/scan_views.py
  src/seedsigner/views/seed_views.py
  src/seedsigner/views/view.py
  tests/base.py
  tests/test_bip85.py
  tests/test_decodepsbtqr.py
  tests/test_encodepsbtqr.py
  tests/test_flows_settings.py
  tests/test_psbt_parser.py
  tests/test_seed.py
Labels: enhancement

#333 [Enhancement] Specific `ScanView` child classes to limit acceptable QR types
  src/seedsigner/gui/screens/scan_screens.py
  src/seedsigner/views/psbt_views.py
  src/seedsigner/views/scan_views.py
  src/seedsigner/views/seed_views.py
  src/seedsigner/views/tools_views.py
  src/seedsigner/views/view.py
  tests/test_flows_psbt.py
  tests/test_flows_tools.py
Labels: enhancement

#423 SeedSigner Icons v2
  .gitignore
  src/seedsigner/gui/components.py
  src/seedsigner/gui/screens/psbt_screens.py
  src/seedsigner/gui/screens/screen.py
  src/seedsigner/gui/screens/seed_screens.py
  src/seedsigner/gui/screens/tools_screens.py
  src/seedsigner/resources/fonts/seedsigner-glyphs.otf
  src/seedsigner/resources/fonts/seedsigner-icons.otf
  src/seedsigner/views/psbt_views.py
  src/seedsigner/views/seed_views.py
  src/seedsigner/views/settings_views.py
  src/seedsigner/views/tools_views.py
  src/seedsigner/views/view.py
  tests/screenshot_generator/README.md
  tests/screenshot_generator/__init__.py
  tests/screenshot_generator/conftest.py
  tests/screenshot_generator/generator.py
  tests/screenshot_generator/utils.py
Labels: enhancement

#262 [New Feature] QR-based message signing
  src/seedsigner/controller.py
  src/seedsigner/gui/components.py
  src/seedsigner/gui/renderer.py
  src/seedsigner/gui/screens/screen.py
  src/seedsigner/gui/screens/seed_screens.py
  src/seedsigner/gui/screens/tools_screens.py
  src/seedsigner/helpers/embit_utils.py
  src/seedsigner/models/decode_qr.py
  src/seedsigner/models/encode_qr.py
  src/seedsigner/models/qr_type.py
  src/seedsigner/models/settings_definition.py
  src/seedsigner/views/psbt_views.py
  src/seedsigner/views/scan_views.py
  src/seedsigner/views/seed_views.py
  src/seedsigner/views/view.py
  tests/base.py
  tests/screenshot_generator/generator.py
  tests/test_embit_utils.py
  tests/test_flows_seed.py
Labels: enhancement

#424 Reminder to remove SD card via Toast notification
  src/seedsigner/controller.py
  src/seedsigner/gui/components.py
  src/seedsigner/gui/screens/screen.py
  src/seedsigner/gui/toast.py
  src/seedsigner/hardware/microsd.py
  src/seedsigner/models/settings.py
  src/seedsigner/models/settings_definition.py
  src/seedsigner/views/screensaver.py
  src/seedsigner/views/view.py
  tests/base.py
  tests/screenshot_generator/generator.py
  tests/test_flows_seed.py
  tests/test_flows_view.py
Labels: enhancement

#443 Message signing network mismatch bugfix; `OptionDisabledView` bugfix
  src/seedsigner/views/scan_views.py
  src/seedsigner/views/seed_views.py
  src/seedsigner/views/view.py
  tests/screenshot_generator/generator.py
  tests/test_flows_seed.py
Labels: bug

#445 [bugfix] Final word calc UI spacing fix; `TextArea` consistency/placement improvements
  src/seedsigner/gui/components.py
  src/seedsigner/gui/screens/tools_screens.py
  src/seedsigner/gui/toast.py
  src/seedsigner/models/seed_storage.py
  src/seedsigner/views/tools_views.py
  tests/screenshot_generator/generator.py
Labels: bug
