Repository SeedSigner/seedsigner, pull requests merged in 2023-09, with the labels that each got.

#461 [Enhancement] Additional edge padding for Warning Screen body text
  src/seedsigner/gui/screens/screen.py
  tests/screenshot_generator/generator.py
Labels: enhancement

#464 [bugfix] Prevent SettingsQR from trying to enable Persistent Settings when SD card is not inserted
  src/seedsigner/gui/screens/scan_screens.py
  src/seedsigner/gui/screens/settings_screens.py
  src/seedsigner/models/settings.py
  src/seedsigner/views/settings_views.py
  tests/base.py
  tests/screenshot_generator/generator.py
  tests/test_flows_settings.py
  tests/test_settings.py
Labels: bug

#436 update manual install instructions
  docs/manual_installation.md
Labels: documentation
