Repository SeedSigner/seedsigner, pull requests merged in 2024-12, with the labels that each got.

#618 [Fix] Nunchuk to use UR Xpub encoding for both single sig and multisig
  src/seedsigner/views/seed_views.py
Labels: bug

#631 Additional SeedQR Templates
  docs/seed_qr/printable_templates/grid_wfingerprint_25x25.pdf
  docs/seed_qr/printable_templates/grid_wfingerprint_29x29.pdf
Labels: documentation

#610 Update encode_qr.py - Fixes #582
  src/seedsigner/models/encode_qr.py
  tests/test_encodepsbtqr.py
Labels: bug, enhancement
